# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
